pageInfo:
  title: Dashboard
  description: Wilson Le Dashboard
  navLinks:
  - title: GitHub
    path: https://github.com/WilsonLe
  - title: Portfolio
    path: https://wilsonle.me
  - title: LinkedIn
    path: https://www.linkedin.com/in/wilsonle02

appConfig:
  theme: colorful

sections:
- name: Content Management Systems
  icon: fas fa-newspaper  
  items:
  - title: HG-CMS
    description: Content Management System for Huong Giang's portfolio
    icon: strapi.png
    url: https://hobby.wilsonle.me/hg-cms/admin
    target: newtab
  - title: ST-CMS
    description: Content Management System for Son Tran's portfolio
    icon: strapi.png
    url: https://hobby.wilsonle.me/st-cms/admin
    target: newtab